logdir: ./log/log_mix_base
dataset_root_dir: ./data/fbank40_new_Norm_mix
labeled_set: train_mix
dev_set: dev_mix
test_set: test_mix
max_feature_length: 2040
min_feature_length: 128
max_text_length: 212
min_text_length: 3
max_dec_timesteps: 220
batch_size: 32
shuffle: True
ls_weight: 0.05
input_dim: 40
enc_hidden_dim: 200
enc_output_dim: 200
enc_n_layers: 2
subsample: [2, 1]
dropout_rate: 0.2
dec_hidden_dim: 200
att_dim: 200
conv_channels: 10
conv_kernel_size: 100
att_odim: 200
embedding_dim: 50
learning_rate: 0.0005
weight_decay: 0.0000001
max_grad_norm: 5
load_model_path: ./models/mix_base/mix_base_best
retrieve_learning_rate: 0.0005
load_optimizer: True
init_tf_rate: 1.0
tf_start_decay_epochs: 70
tf_rate_lowerbound: 1.0
tf_decay_epochs: 130
epochs: 300
add_gaussian: False
gaussian_epoch: 20
gaussian_std: 0.075
tag: mix
model_dir: ./models/mix_base
model_name: mix_base
vocab_path: ./data/fbank40_new_Norm_mix/vocab_dict.p
non_lang_syms_path: ./data/fbank40_new_Norm_mix/non_lang_syms.p
sample_num: 5
early_stop_start_epoch: 180
early_stop: 30
test_file_name: test/predict_mix_base
z_data_path: z_data/mix_base.p
