logdir: ./log/log_chime3_base
dataset_root_dir: ./data/fbank40_new_Norm_addsimu
labeled_set: train
dev_set: dev
test_set: test
max_feature_length: 2040
min_feature_length: 128
max_text_length: 212
min_text_length: 3
max_dec_timesteps: 220
batch_size: 32
shuffle: True
ls_weight: 0.05
input_dim: 40
enc_hidden_dim: 200
enc_output_dim: 200
enc_n_layers: 2
subsample: [2, 1]
dropout_rate: 0.2
dec_hidden_dim: 200
att_dim: 200
conv_channels: 10
conv_kernel_size: 100
att_odim: 200
embedding_dim: 50
learning_rate: 0.0005
weight_decay: 0.000001
max_grad_norm: 5
load_model_path: ./models/chime3_base/chime3_noisy_best
retrieve_learning_rate: 0.0005
load_optimizer: True
init_tf_rate: 1.0
tf_start_decay_epochs: 70
tf_rate_lowerbound: 1.0
tf_decay_epochs: 150
epochs: 300
add_gaussian: False
gaussian_epoch: 20
gaussian_std: 0.075
tag: chime3
model_dir: ./models/chime3_base
model_name: chime3_base
vocab_path: ./data/fbank40_new_Norm_addsimu/vocab_dict.p
non_lang_syms_path: ./data/fbank40_new_Norm_addsimu/non_lang_syms.p
sample_num: 5
early_stop_start_epoch: 180
early_stop: 30
test_file_name: test/predict_chime_base
z_data_path: z_data/chime_base.p
